//
//  BViewController.swift
//  CoordinatorTransitons
//
//  Created by Pavle Pesic on 5/18/18.
//  Copyright (c) 2018 Pavle Pesic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BViewControllerProtocol: BaseViewControllerProtocol {
    var onPopToAWithFade: (() -> Void)? { get set }
    var onGoToSecondCoordinator: (() -> Void)? { get set }
}

class BViewController: UIViewController, BViewControllerProtocol {
    
    // MARK: - Vars & Lets
    
    var viewModel: BViewModelDelegate?
    
    // MARK: - BViewControllerProtocol
    
    var onPopToAWithFade: (() -> Void)?
    var onGoToSecondCoordinator: (() -> Void)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        self.viewModel = BViewModel()
    }
    
    // MARK: - Controller lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - Actions
    
    @IBAction func actionPopToWithFade() {
        self.onPopToAWithFade?()
    }
    
    @IBAction func actionGoToSecondCoordinator() {
        self.onGoToSecondCoordinator?()
    }
    
}
