//
//  CViewController.swift
//  CoordinatorTransitons
//
//  Created by Pavle Pesic on 5/18/18.
//  Copyright (c) 2018 Pavle Pesic. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CViewControllerProtocol: BaseViewControllerProtocol {
    var onGoToD: (() -> Void)? { get set }
    var onPopToB: (() -> Void)? { get set }
}

class CViewController: UIViewController, CViewControllerProtocol {
    
    // MARK: - Vars & Lets
    
    var viewModel: CViewModelDelegate?
    
    // MARK: - CViewControllerProtocol
    
    var onGoToD: (() -> Void)?
    var onPopToB: (() -> Void)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        self.viewModel = CViewModel()
    }
    
    // MARK: - Controller lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - Actions
    
    @IBAction func actionGoToD() {
        self.onGoToD?()
    }
    
    @IBAction func actionBack() {
        self.onPopToB?()
    }
    
}
